set_property(GLOBAL PROPERTY USE_FOLDERS ON)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/dist")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/dist")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/dist")

add_compile_options("/W0")
add_compile_options("/sdl-")
add_compile_options("/MP")
add_compile_options("/Zi")
add_compile_options("/Od")
add_compile_options("/Oi")
add_compile_options("/GL-")
add_compile_options("/GF")
add_compile_options("/EHs")
add_compile_options("/GS-")
add_compile_options("/Gy")
add_compile_options("/guard:cf-")
add_compile_options("/FI${CMAKE_CURRENT_SOURCE_DIR}/VisualUefi/EDK-II/BaseLib/vshacks.h")

add_link_options("/NODEFAULTLIB")
add_link_options("/WX:NO")
add_link_options("/MANIFEST:NO")
add_link_options("/DEBUG:FASTLINK")
add_link_options("/SUBSYSTEM:EFI_APPLICATION")
add_link_options("/Driver")
add_link_options("/OPT:REF")
add_link_options("/OPT:ICF")
add_link_options("/LTCG")
add_link_options("/ENTRY:EfiMain")
add_link_options("/BASE:0")
add_link_options("/merge:.rdata=.data")
add_link_options("/ALIGN:32")
add_link_options("/SAFESEH:NO")
add_link_options("/DYNAMICBASE:NO")
add_link_options("/NXCOMPAT:NO")
